FROM python:3.9-slim

WORKDIR /app

# Install dependencies
RUN pip install flask docker

# Copy server code
COPY server.py /app/server.py
COPY templates /app/templates
COPY heartbeat.py /app/heartbeat.py

# Expose port
EXPOSE 5000

# Run the server
CMD ["python", "server.py"]